### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by Command435-CRM**

### CODE REVIEW

**Comment by l4zs** [comment]
thank you, although i would suppose naming it 1.20.1 if its for 1.20.1

**Comment by Command435-CRM** [comment]
But kspigot version 1.19.2 is for 1.19.4. Your version naming scheme doesn't make sense.

**Comment by ChristopherBStocks** [comment]
> But kspigot version 1.19.2 is for 1.19.4. Your version naming scheme doesn't make sense.

1.19.2 KSpigot is compatible with 1.19.4.

1.20.1 KSpigot would have to be for 1.20.1 for your naming to make sense. It is 1.20 with compatibility for 1.20.1

**Comment by Command435-CRM** [comment]
I renamed it

**Comment by jakobkmar** [comment]
> thank you, although i would suppose naming it 1.20.1 if its for 1.20.1

Until now, the scheme was `majorminecraftversion.kspigotrevision`, which still leads to confusion, we could change it with this release - or just leave it as it is (which would be `1.20.0`, as @Command435-CRM initially did).

**Comment by l4zs** [comment]
i think now we have less confusion

**Pull request merged**
