### PR TITLE
Bump to mc 1.20.4

### PR DESCRIPTION
**Pull request by mgvpri**
- Bump paperweight/bukkit version to 1.20.4
  - Changed Location.spawnCleanEntity according to method-name change in craftbukkit api
- Change .values() to .entries for iterating over enums

### CODE REVIEW

**Comment by kxmpxtxnt** [comment]
Not exactly sure about the versioning. I thought the kspigot version was not mirrored with the current mc version.
Iirc 1.20.2 (Kspigot) also supported 1.20.3 (Mc)

**Comment by ChristopherBStocks** [comment]
> Not exactly sure about the versioning. I thought the kspigot version was not mirrored with the current mc version.
> 
> Iirc 1.20.2 (Kspigot) also supported 1.20.3 (Mc)

Yeah, iirc, it mirrors the 1.20 but for the last, it would be the build, so in this case 1.20.3 not 1.20.4

**Comment by mgvpri** [comment]
I fixed the version, now its 1.20.3

**Review by jakobkmar — APPROVED** [review]
Thank you!

**Pull request merged**
