### PR TITLE
Switch to GPL 3.0

### PR DESCRIPTION
**Pull request by jakobkmar**

### CODE REVIEW

**Comment by jakobkmar** [comment]
@NyCodeGHG @F0Xde @l4zs @Skyslycer @Hotkeyyy @r0yzer Do you approve this license change? Only after your reaction I am able to merge this PR.

**Review by Hotkeyyy — APPROVED** [review]

**Review by r0yzer — APPROVED** [review]

**Review by l4zs — APPROVED** [review]

**Review by F0Xde — APPROVED** [review]

**Comment by Skyslycer** [comment]
Would that restrict using kSpigot in private repos?

**Review by NyCodeGHG — APPROVED** [review]

**Comment by jakobkmar** [comment]
It wouldn't "restrict" that, but you have to provide the class where you inherit from `KSpigot` upon request.

In reality however, I won't enforce this at any time. This is just to comply with Bukkits license.

In the end, it is the same as using Paper or Spigot or Bukkit "restricts" you.

**Comment by NyCodeGHG** [comment]
> Would that restrict using kSpigot in private repos?

I am not a lawyer, but to my knowledge, a user of the plugin must be provided the source code. The user is the one who installs the plugin on the server, but the players themselves are not, because that falls under network use and is only covered by the AGPL license.

**Comment by jakobkmar** [comment]
KSpigot has to do the same as any other project in this ecosystem. For example paper inherits GPL 3.0 as well <https://github.com/PaperMC/Paper/blob/master/LICENSE.md>

It's just the reality that a lot of people ignore this and violate the GPL every day, but I won't do this with KSpigot anymore.

**Review by Skyslycer — APPROVED** [review]

**Comment by r0yzer** [comment]
krank wie kspigot den basti ghg coder fast ins gefängnis gebracht hat puh knappe sache

**Comment by r0yzer** [comment]
deshalb liebe leute fabric nutzen das wort zum sonntag

**Pull request merged**
